[default]
address = "127.0.0.1"
port = 7002
workers = 16
max_blocking = 512
keep_alive = 5
ident = "Rocket"
log_level = "normal"
cli_colors = true
secret_key = "hPRYyVRiMyxpw5sBB1XeCMN1kFsDCqKvBi2QJxBVHQk="

[default.limits]
form = "64 kB"
json = "1 MiB"
msgpack = "2 MiB"
"file/jpg" = "5 MiB"

[default.shutdown]
ctrlc = true
signals = ["term", "hup"]
grace = 5
mercy = 5